name: financas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.13.10
  go_router: ^17.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
